### ISSUE TITLE
navExpanded not able to be set to false

### ISSUE THREAD

**Issue by trentgillham** [PredixDev/px-app-nav#7]
I am trying to set the navigation to be collapsed by default, but `<px-app-nav nav-expanded="false" ....> </px-app-nav> ` doesn't seem to do anything. Is there some other property that needs to be set?

**Comment by benschenker** [comment]
You can add the class `navbar--collapsed` to the `px-app-nav` tag but then it will not correctly expand (if the user clicks on the navbar toggle)

**Comment by yashdoshi89** [comment]
It's fixed in version px-app-nav 1.1.0 Here's the link: https://github.com/PredixDev/px-app-nav/releases/tag/v1.1.0

For a Boolean property to be configurable from markup, it must default to false. If it defaults to true, you cannot set it to false from markup, since the presence of the attribute, with or without a value, equates to true. This is the standard behavior for attributes in the web platform.

You can read more about it here: https://www.polymer-project.org/1.0/docs/devguide/properties.html#attribute-deserialization

We have made code changes to incorporate this functionality so you will be able to use nav expanded collapsed property

**Comment by benschenker** [comment]
Hey thanks for the response!

I upgraded to 1.1.0 and the setting `nav-expanded="false"` still has no effect...

**Comment by trentgillham** [comment]
Same with me, still doesn't work. I've also noticed that if you use the **navbar--collapsed** and **navbar--text-hidden** classes to make the nav bar collapsed by default, it makes the opening animation jerk oddly.

**Comment by ek** [comment]
We're looking into this now... will follow up.

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by yashdoshi89** [comment]
@benschenker @trentgillham We have fixed it now and also added it to the demo page to test it easily. Please let us know if this fixes your issue. Please pull latest and test it out.
